task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the marker in the silver pot
instruction_obj_to_replace: marker
instruction_target_to_replace: pot
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.3096869
    - 0.4987724
    - 0.2572133
    rot:
    - 0.5101872
    - -0.4797542
    - -0.6653733
    - 0.2585022
  cam2:
    pos:
    - -0.0546644
    - -0.5556831
    - 0.2723456
    rot:
    - 0.7610307
    - 0.1051705
    - -0.5098575
    - 0.3870617
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.056298
target_objects:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0906387
distractors:
- type: DatasetObject
  name: distractor_cherry_tomato
  category: cherry_tomato
  model: dqvtgm
  bounding_box:
  - 0.0315681
  - 0.0193244
  - 0.0242142
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0621071
- type: DatasetObject
  name: distractor_tablefork
  category: tablefork
  model: uodzrq
  bounding_box:
  - 0.1
  - 0.0126529
  - 0.0063285
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.0531643
- type: DatasetObject
  name: distractor_screwdriver
  category: screwdriver
  model: uajlga
  bounding_box:
  - 0.1
  - 0.0092784
  - 0.0092209
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0546105
immutables: []
