task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the white cloth from the plate
instruction_obj_to_replace: cloth
instruction_target_to_replace: plate
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_1_int:
  - Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0968786
    - 0.7448001
    - 0.4066148
    rot:
    - 0.1570403
    - -0.6751912
    - -0.6827666
    - 0.2308354
  cam2:
    pos:
    - -0.1370631
    - -0.6969172
    - 0.4550239
    rot:
    - 0.6389801
    - -0.2745084
    - -0.2912994
    - 0.6568822
main_objects:
- type: DatasetObject
  name: cloth
  category: microfiber_cloth
  model: zpllxb
  bounding_box:
  - 0.14
  - 0.1399976
  - 0.0012591
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.0604118
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_hamper
  category: hamper
  model: qhdikw
  bounding_box:
  - 0.1
  - 0.1
  - 0.1501503
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.455
  - 0.1250752
- type: DatasetObject
  name: distractor_apple
  category: apple
  model: rizrsp
  bounding_box:
  - 0.0369395
  - 0.0413219
  - 0.0412187
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.455
  - 0.0706094
- type: DatasetObject
  name: distractor_grape
  category: grape
  model: uprbwp
  bounding_box:
  - 0.1
  - 0.0617632
  - 0.0602211
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.195
  - 0.0801106
immutables:
- type: DatasetObject
  name: plate
  category: plate
  model: itoeew
  bounding_box:
  - 0.17
  - 0.17
  - 0.010097
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.0550485
