task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: stack
instruction: Put the masking tape on the plate
instruction_obj_to_replace: masking tape
instruction_target_to_replace: plate
instruction_verb_to_replace: stack
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - -0.0518017
    - -0.2971175
    - 0.2067697
    rot:
    - 0.494668
    - -0.3077903
    - -0.4273015
    - 0.6913625
  cam2:
    pos:
    - -0.1017784
    - 0.5184805
    - 0.6411688
    rot:
    - 0.3272091
    - -0.4359507
    - -0.6668735
    - 0.5080954
main_objects:
- type: DatasetObject
  name: tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0557962
target_objects:
- type: DatasetObject
  name: plate
  category: plate
  model: itoeew
  bounding_box:
  - 0.17
  - 0.17
  - 0.010097
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0550485
distractors:
- type: DatasetObject
  name: distractor_lemon
  category: lemon
  model: bbvonm
  bounding_box:
  - 0.0568493
  - 0.0475621
  - 0.0454882
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0727442
- type: DatasetObject
  name: distractor_beefsteak_tomato
  category: beefsteak_tomato
  model: eevvzv
  bounding_box:
  - 0.0551043
  - 0.0539619
  - 0.0716401
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0858201
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0538992
immutables: []
