task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the pen from the mug cup
instruction_obj_to_replace: pen
instruction_target_to_replace: mug cup
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.1968277
    - -0.324219
    - 0.3181274
    rot:
    - 0.452178
    - -0.1808461
    - -0.3730423
    - 0.7897273
  cam2:
    pos:
    - 0.2253613
    - 0.3961705
    - 0.3016106
    rot:
    - 0.1905946
    - -0.5275468
    - -0.7703491
    - 0.3032001
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.1437248
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_screwdriver
  category: screwdriver
  model: uajlga
  bounding_box:
  - 0.1
  - 0.0092784
  - 0.0092209
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0546105
- type: DatasetObject
  name: distractor_egg
  category: egg
  model: qopwgx
  bounding_box:
  - 0.0656635
  - 0.051892
  - 0.0518489
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0759245
- type: DatasetObject
  name: distractor_tongs
  category: tongs
  model: rcpjld
  bounding_box:
  - 0.1
  - 0.0257111
  - 0.0243122
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.0621561
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0819912
