task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the pen from the cup
instruction_obj_to_replace: pen
instruction_target_to_replace: cup
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.2022817
    - -0.3198482
    - 0.3167347
    rot:
    - 0.4503326
    - -0.1759914
    - -0.3707248
    - 0.7929632
  cam2:
    pos:
    - 0.2331655
    - 0.3935454
    - 0.2976625
    rot:
    - 0.1844018
    - -0.5277619
    - -0.7718747
    - 0.3027752
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.1437248
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_tablefork
  category: tablefork
  model: uodzrq
  bounding_box:
  - 0.1
  - 0.0126529
  - 0.0063285
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.0531643
- type: DatasetObject
  name: distractor_papaya
  category: papaya
  model: zsdzix
  bounding_box:
  - 0.1
  - 0.0566961
  - 0.0578202
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.0789102
- type: DatasetObject
  name: distractor_rubber_eraser
  category: rubber_eraser
  model: cungod
  bounding_box:
  - 0.05
  - 0.0213523
  - 0.0114031
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0557016
immutables:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0819912
