task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the pen from the cup
instruction_obj_to_replace: pen
instruction_target_to_replace: cup
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_0_int:
  - Coffee_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2818215
    - 0.6385262
    - 0.3137613
    rot:
    - 0.0452655
    - -0.5336004
    - -0.8351375
    - 0.1255672
  cam2:
    pos:
    - 0.2429605
    - -0.486982
    - 0.3725216
    rot:
    - 0.6105592
    - -0.0404723
    - -0.1155514
    - 0.7824496
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.11
  - 0.099
  - 0.1437248
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.36
  - 0.306
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.1
  - 0.324
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.38
  - 0.099
  - 0.0562801
immutables:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.11
  - 0.099
  - 0.0819912
