task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the mug cup
instruction_obj_to_replace: marker
instruction_target_to_replace: mug cup
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.2522517
    - -0.4582312
    - 0.4944536
    rot:
    - 0.6211908
    - -0.2248103
    - -0.2451231
    - 0.7095752
  cam2:
    pos:
    - 0.261682
    - 0.5761531
    - 0.5222775
    rot:
    - 0.2737522
    - -0.5719814
    - -0.6920135
    - 0.3449846
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.1390538
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teapot
  category: teapot
  model: mvrhya
  bounding_box:
  - 0.1
  - 0.0622266
  - 0.0388673
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.0694337
- type: DatasetObject
  name: distractor_scone
  category: scone
  model: gwdhyj
  bounding_box:
  - 0.1
  - 0.0635422
  - 0.0342754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.0671377
- type: DatasetObject
  name: distractor_tongs
  category: tongs
  model: rcpjld
  bounding_box:
  - 0.1
  - 0.0257111
  - 0.0243122
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0621561
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0819912
