task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the pen in the bowl
instruction_obj_to_replace: pen
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.1349881
    - 0.3569105
    - 0.468794
    rot:
    - 0.1434189
    - -0.5170226
    - -0.7781702
    - 0.3264503
  cam2:
    pos:
    - 0.0573524
    - -0.3685903
    - 0.3876676
    rot:
    - 0.4399351
    - -0.2921687
    - -0.4419136
    - 0.7251255
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1257811
  - 0.0112061
  - 0.0099033
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0549517
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_chopstick
  category: chopstick
  model: bdvjuf
  bounding_box:
  - 0.1
  - 0.0022828
  - 0.002288
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.051144
- type: DatasetObject
  name: distractor_baseball
  category: baseball
  model: zanmar
  bounding_box:
  - 0.0734651
  - 0.0734803
  - 0.0734952
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0867477
- type: DatasetObject
  name: distractor_screwdriver
  category: screwdriver
  model: uajlga
  bounding_box:
  - 0.1
  - 0.0092784
  - 0.0092209
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0546105
immutables: []
