task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick the pen and put it in the cup
instruction_obj_to_replace: pen
instruction_target_to_replace: cup
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.0583461
    - 0.4453376
    - 0.277806
    rot:
    - 0.1740339
    - -0.4557661
    - -0.7575837
    - 0.4336547
  cam2:
    pos:
    - 0.1044113
    - -0.4444046
    - 0.3031941
    rot:
    - 0.5380507
    - -0.1361596
    - -0.1741744
    - 0.8134035
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.0546835
target_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_cherry_tomato
  category: cherry_tomato
  model: dqvtgm
  bounding_box:
  - 0.0315681
  - 0.0193244
  - 0.0242142
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.0621071
- type: DatasetObject
  name: distractor_banana
  category: banana
  model: verqwv
  bounding_box:
  - 0.1
  - 0.0313722
  - 0.0157945
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0578973
- type: DatasetObject
  name: distractor_stapler
  category: stapler
  model: kgnsas
  bounding_box:
  - 0.0874299
  - 0.0182303
  - 0.0450232
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.25
  - 0.0725117
immutables: []
