task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the spoon in the mug
instruction_obj_to_replace: spoon
instruction_target_to_replace: mug
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.3148717
    - -0.5097999
    - 0.2412254
    rot:
    - 0.5098508
    - -0.1718114
    - -0.1345156
    - 0.8321289
  cam2:
    pos:
    - 0.2783204
    - 0.5206427
    - 0.3995096
    rot:
    - 0.0873014
    - -0.5168748
    - -0.8266392
    - 0.204662
main_objects:
- type: DatasetObject
  name: spoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.0538992
target_objects:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_volleyball
  category: volleyball
  model: nofzds
  bounding_box:
  - 0.0997848
  - 0.1
  - 0.1000092
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.1000046
- type: DatasetObject
  name: distractor_baseball
  category: baseball
  model: zanmar
  bounding_box:
  - 0.0734651
  - 0.0734803
  - 0.0734952
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0867477
- type: DatasetObject
  name: distractor_box_of_cereal
  category: box_of_cereal
  model: pfwgkm
  bounding_box:
  - 0.035
  - 0.1
  - 0.115
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.1075001
immutables: []
