task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the marker out of the mug.
instruction_obj_to_replace: marker
instruction_target_to_replace: ''
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2054415
    - -0.5546227
    - 0.5321386
    rot:
    - 0.3994296
    - -0.0434929
    - -0.1703865
    - 0.8997404
  cam2:
    pos:
    - 0.3078082
    - 0.3944114
    - 0.4355454
    rot:
    - 0.076544
    - -0.4271702
    - -0.8805483
    - 0.1905291
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.132
  - 0.088
  - 0.056298
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.432
  - 0.272
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.288
  - 0.0557962
- type: DatasetObject
  name: distractor_pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1
  - 0.0089092
  - 0.0078734
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.456
  - 0.088
  - 0.0539367
immutables: []
