task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the bowl
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - -0.0417649
    - -0.4172776
    - 0.4773761
    rot:
    - 0.5634163
    - -0.3080634
    - -0.3648458
    - 0.6742007
  cam2:
    pos:
    - -0.0242969
    - 0.5447628
    - 0.3883012
    rot:
    - 0.3056603
    - -0.598816
    - -0.68285
    - 0.2858446
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.1232469
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_tennis_ball
  category: tennis_ball
  model: rgekxe
  bounding_box:
  - 0.0667253
  - 0.0658372
  - 0.0659834
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0829917
- type: DatasetObject
  name: distractor_pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1
  - 0.0089092
  - 0.0078734
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0539367
- type: DatasetObject
  name: distractor_canned_food
  category: canned_food
  model: byakrm
  bounding_box:
  - 0.0577961
  - 0.0577961
  - 0.081812
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.090906
immutables:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0740878
