task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: stack
instruction: Put the lid on the pan
instruction_obj_to_replace: lid
instruction_target_to_replace: pan
instruction_verb_to_replace: stack
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.117059
    - 0.4970365
    - 0.2076592
    rot:
    - 0.2922263
    - -0.5521227
    - -0.7025259
    - 0.3409131
  cam2:
    pos:
    - 0.2184833
    - -0.3888698
    - 0.4974716
    rot:
    - 0.4628943
    - -0.1194043
    - -0.2677133
    - 0.8365411
main_objects:
- type: DatasetObject
  name: lid
  category: lid
  model: zkderg
  bounding_box:
  - 0.0761192
  - 0.0761192
  - 0.0330479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.132
  - 0.088
  - 0.066524
target_objects:
- type: DatasetObject
  name: pan
  category: frying_pan
  model: cprjvq
  bounding_box:
  - 0.22
  - 0.1407512
  - 0.0344362
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.432
  - 0.272
  - 0.0672181
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.288
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.456
  - 0.088
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.288
  - 0.172
  - 0.0562801
immutables: []
