task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the pen from the cup and put it on the table
instruction_obj_to_replace: pen
instruction_target_to_replace: ''
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_0_int:
  - Coffee_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2266933
    - -0.3501627
    - 0.4555041
    rot:
    - 0.3022085
    - -0.2196484
    - -0.4691357
    - 0.8002102
  cam2:
    pos:
    - 0.3626746
    - 0.2983627
    - 0.3372155
    rot:
    - 0.1313415
    - -0.3919619
    - -0.7741005
    - 0.4794619
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1257811
  - 0.0112061
  - 0.0099033
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.11
  - 0.099
  - 0.0549517
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.36
  - 0.306
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.1
  - 0.324
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.38
  - 0.099
  - 0.0562801
immutables: []
