task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the pot
instruction_obj_to_replace: marker
instruction_target_to_replace: pot
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.0288801
    - 0.5209215
    - 0.5609241
    rot:
    - 0.3891626
    - -0.5943457
    - -0.5713328
    - 0.4109557
  cam2:
    pos:
    - 0.0783043
    - -0.6548508
    - 0.4519616
    rot:
    - 0.6005859
    - -0.2269652
    - -0.246918
    - 0.7258201
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.1563488
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_broccoli
  category: broccoli
  model: wsxavx
  bounding_box:
  - 0.029087
  - 0.0290308
  - 0.0218591
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.0609296
- type: DatasetObject
  name: distractor_allen_wrench
  category: allen_wrench
  model: neqlcn
  bounding_box:
  - 0.1
  - 0.0216
  - 0.0037425
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.0518713
- type: DatasetObject
  name: distractor_pear
  category: pear
  model: clvnqe
  bounding_box:
  - 0.0933374
  - 0.0726271
  - 0.0773291
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0886646
immutables:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0906387
