task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the pen from the mug cup
instruction_obj_to_replace: pen
instruction_target_to_replace: mug cup
instruction_verb_to_replace: pick
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.0030139
    - 0.4862828
    - 0.2859611
    rot:
    - 0.2491597
    - -0.4435746
    - -0.7587701
    - 0.4067296
  cam2:
    pos:
    - 0.2163908
    - -0.5832136
    - 0.4230995
    rot:
    - 0.5168552
    - -0.0502789
    - -0.1643419
    - 0.8386444
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.1437248
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_parer
  category: parer
  model: zpkhwi
  bounding_box:
  - 0.1
  - 0.0126289
  - 0.006733
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0533665
- type: DatasetObject
  name: distractor_blackboard_eraser
  category: blackboard_eraser
  model: oynrtw
  bounding_box:
  - 0.1
  - 0.0333333
  - 0.0242238
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0621119
- type: DatasetObject
  name: distractor_hamburger
  category: hamburger
  model: fyswch
  bounding_box:
  - 0.1
  - 0.0931673
  - 0.0648095
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0824048
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0819912
