task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the mug
instruction_obj_to_replace: marker
instruction_target_to_replace: mug
instruction_verb_to_replace: pick
supported_scenes:
  office_cubicles_left:
  - Circular_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0745989
    - -0.74645
    - 0.5737398
    rot:
    - 0.5343445
    - 0.0774171
    - -0.4052086
    - 0.7377591
  cam2:
    pos:
    - 0.1983293
    - 0.648044
    - 0.4065467
    rot:
    - 0.1969998
    - -0.4997466
    - -0.7725577
    - 0.3385249
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.132
  - 0.11
  - 0.1390538
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.432
  - 0.34
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.36
  - 0.0557962
- type: DatasetObject
  name: distractor_pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1
  - 0.0089092
  - 0.0078734
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.456
  - 0.11
  - 0.0539367
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.132
  - 0.11
  - 0.0819912
