task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: stack
instruction: Stack up the cups
instruction_obj_to_replace: cups
instruction_target_to_replace: cups
instruction_verb_to_replace: stack
supported_scenes:
  Pomaria_1_int:
  - Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0163074
    - 0.4838995
    - 0.4628079
    rot:
    - 0.2617662
    - -0.5646288
    - -0.7181223
    - 0.311405
  cam2:
    pos:
    - 0.089452
    - -0.2295199
    - 0.4644402
    rot:
    - 0.4693765
    - -0.3749618
    - -0.5143877
    - 0.6119597
main_objects:
- type: DatasetObject
  name: cup_1
  category: mug
  model: kitxam
  bounding_box:
  - 0.0640022
  - 0.0858475
  - 0.0646612
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.455
  - 0.0823306
target_objects:
- type: DatasetObject
  name: cup_2
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_chestnut
  category: chestnut
  model: fmomat
  bounding_box:
  - 0.0199921
  - 0.0153447
  - 0.0153222
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.455
  - 0.0576611
- type: DatasetObject
  name: distractor_peach
  category: peach
  model: wrutgk
  bounding_box:
  - 0.0884365
  - 0.0909698
  - 0.0949293
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.195
  - 0.0974647
- type: DatasetObject
  name: distractor_teapot
  category: teapot
  model: mvrhya
  bounding_box:
  - 0.1
  - 0.0622266
  - 0.0388673
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.325
  - 0.0694337
immutables: []
