task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: stack
instruction: Stack the cups
instruction_obj_to_replace: cups
instruction_target_to_replace: cups
instruction_verb_to_replace: stack
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2171558
    - 0.5828796
    - 0.6050775
    rot:
    - 0.1611323
    - -0.4321474
    - -0.8478327
    - 0.2616576
  cam2:
    pos:
    - 0.002558
    - -0.2521949
    - 0.6739561
    rot:
    - 0.4262998
    - -0.3233974
    - -0.5008318
    - 0.6803308
main_objects:
- type: DatasetObject
  name: cup_1
  category: mug
  model: kitxam
  bounding_box:
  - 0.0640022
  - 0.0858475
  - 0.0646612
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0823306
target_objects:
- type: DatasetObject
  name: cup_2
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_pomelo
  category: pomelo
  model: ezckjt
  bounding_box:
  - 0.0882033
  - 0.072013
  - 0.0732954
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0866477
- type: DatasetObject
  name: distractor_gooseberry
  category: gooseberry
  model: cltzwx
  bounding_box:
  - 0.0142568
  - 0.0126678
  - 0.0128769
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.0564385
- type: DatasetObject
  name: distractor_papaya
  category: papaya
  model: zsdzix
  bounding_box:
  - 0.1
  - 0.0566961
  - 0.0578202
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0789102
immutables: []
