task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the orange cup inside the black bowl
instruction_obj_to_replace: cup
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2837592
    - -0.2203568
    - 0.2084706
    rot:
    - 0.410119
    - -0.2031927
    - -0.4484581
    - 0.7677242
  cam2:
    pos:
    - 0.2509776
    - 0.2684489
    - 0.3132483
    rot:
    - 0.1873814
    - -0.3427803
    - -0.8108428
    - 0.4358025
main_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: kitxam
  bounding_box:
  - 0.0640022
  - 0.0858475
  - 0.0646612
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.455
  - 0.0823306
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.455
  - 0.0538992
- type: DatasetObject
  name: distractor_teapot
  category: teapot
  model: mvrhya
  bounding_box:
  - 0.1
  - 0.0622266
  - 0.0388673
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.195
  - 0.0694337
- type: DatasetObject
  name: distractor_peach
  category: peach
  model: wrutgk
  bounding_box:
  - 0.0884365
  - 0.0909698
  - 0.0949293
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.325
  - 0.0974647
immutables: []
