task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the marker into the mug.
instruction_obj_to_replace: marker
instruction_target_to_replace: mug
instruction_verb_to_replace: put
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.3534913
    - 0.6560805
    - 0.4503228
    rot:
    - 0.185996
    - -0.4800473
    - -0.8100367
    - 0.2807144
  cam2:
    pos:
    - 0.3137135
    - -0.3207173
    - 0.452506
    rot:
    - 0.4965677
    - -0.1755696
    - -0.2206442
    - 0.8209214
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.056298
target_objects:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_zucchini
  category: zucchini
  model: yhhkxf
  bounding_box:
  - 0.1
  - 0.0399945
  - 0.0373826
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0686914
- type: DatasetObject
  name: distractor_broccoli
  category: broccoli
  model: wsxavx
  bounding_box:
  - 0.029087
  - 0.0290308
  - 0.0218591
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0609296
- type: DatasetObject
  name: distractor_allen_wrench
  category: allen_wrench
  model: neqlcn
  bounding_box:
  - 0.1
  - 0.0216
  - 0.0037425
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0518713
immutables: []
