task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the silver lid from the silver pot
instruction_obj_to_replace: silver lid
instruction_target_to_replace: pot
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.3808541
    - 0.572304
    - 0.6183367
    rot:
    - 0.1159369
    - -0.4467552
    - -0.8460237
    - 0.2668564
  cam2:
    pos:
    - 0.3089831
    - -0.2831485
    - 0.5976042
    rot:
    - 0.4022971
    - -0.2744204
    - -0.4094155
    - 0.7715112
main_objects:
- type: DatasetObject
  name: lid
  category: lid
  model: zkderg
  bounding_box:
  - 0.0761192
  - 0.0761192
  - 0.0330479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.1578014
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_pomelo
  category: pomelo
  model: ezckjt
  bounding_box:
  - 0.0882033
  - 0.072013
  - 0.0732954
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0866477
- type: DatasetObject
  name: distractor_wooden_spoon
  category: wooden_spoon
  model: aeubta
  bounding_box:
  - 0.0607686
  - 0.0151325
  - 0.0039479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.051974
- type: DatasetObject
  name: distractor_drill
  category: drill
  model: nzgmza
  bounding_box:
  - 0.0372309
  - 0.1
  - 0.1252277
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.1126139
immutables:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0906387
