task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick up the pen and put it in the cup
instruction_obj_to_replace: pen
instruction_target_to_replace: cup
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2526539
    - -0.5477434
    - 0.5557863
    rot:
    - 0.3800836
    - -0.0225335
    - -0.1604673
    - 0.9106475
  cam2:
    pos:
    - 0.3170717
    - 0.3995286
    - 0.4222223
    rot:
    - 0.0640212
    - -0.4376227
    - -0.8705161
    - 0.2158457
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0546835
target_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_glue_stick
  category: glue_stick
  model: sqzyci
  bounding_box:
  - 0.0947761
  - 0.0192281
  - 0.0192804
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0596402
- type: DatasetObject
  name: distractor_lemon
  category: lemon
  model: bbvonm
  bounding_box:
  - 0.0568493
  - 0.0475621
  - 0.0454882
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.0727442
- type: DatasetObject
  name: distractor_carrot
  category: carrot
  model: nktmff
  bounding_box:
  - 0.0912197
  - 0.0260657
  - 0.0236784
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0618392
immutables: []
