task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the pen in the cup
instruction_obj_to_replace: pen
instruction_target_to_replace: cup
instruction_verb_to_replace: put
supported_scenes:
  Wainscott_0_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0885902
    - -0.1498741
    - 0.3804512
    rot:
    - 0.3361192
    - -0.1933282
    - -0.4428897
    - 0.8083915
  cam2:
    pos:
    - 0.2599938
    - 0.4048629
    - 0.2511806
    rot:
    - 0.1816734
    - -0.5222557
    - -0.7721121
    - 0.3131878
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.35
  - 0.42
  - 0.0546835
target_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.18
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_shaker
  category: shaker
  model: hbheag
  bounding_box:
  - 0.03577
  - 0.0359248
  - 0.091956
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.42
  - 0.0959781
- type: DatasetObject
  name: distractor_pocketknife
  category: pocketknife
  model: ngtgdn
  bounding_box:
  - 0.1
  - 0.0215911
  - 0.0058475
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.35
  - 0.18
  - 0.0529238
- type: DatasetObject
  name: distractor_lime
  category: lime
  model: iwjcjp
  bounding_box:
  - 0.0780001
  - 0.059701
  - 0.0595602
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.25
  - 0.3
  - 0.0797802
immutables: []
