task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the marker from the cup
instruction_obj_to_replace: marker
instruction_target_to_replace: cup
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0055306
    - 0.6779847
    - 0.3255358
    rot:
    - 0.2414414
    - -0.4785484
    - -0.7858182
    - 0.3085242
  cam2:
    pos:
    - 0.1707624
    - -0.5475049
    - 0.2671664
    rot:
    - 0.5968282
    - -0.1411708
    - -0.2233132
    - 0.7576267
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.1390538
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_reagent_bottle
  category: reagent_bottle
  model: uaijua
  bounding_box:
  - 0.0902924
  - 0.0902924
  - 0.1847585
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.1423793
- type: DatasetObject
  name: distractor_banana
  category: banana
  model: verqwv
  bounding_box:
  - 0.1
  - 0.0313722
  - 0.0157945
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0578973
- type: DatasetObject
  name: distractor_wooden_spoon
  category: wooden_spoon
  model: aeubta
  bounding_box:
  - 0.0607686
  - 0.0151325
  - 0.0039479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.051974
immutables:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0819912
