task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the green block in the bowl
instruction_obj_to_replace: block
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.0741523
    - 0.3726577
    - 0.5477247
    rot:
    - 0.2382781
    - -0.5209891
    - -0.7450591
    - 0.3415858
  cam2:
    pos:
    - 0.1319123
    - -0.5628819
    - 0.5177217
    rot:
    - 0.581929
    - -0.1718203
    - -0.2549723
    - 0.7528782
main_objects:
- type: PrimitiveObject
  name: green_block
  primitive_type: Cube
  rgba:
  - 0.1
  - 0.7
  - 0.25
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_apple
  category: apple
  model: rizrsp
  bounding_box:
  - 0.0369395
  - 0.0413219
  - 0.0412187
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0706094
- type: DatasetObject
  name: distractor_shaker
  category: shaker
  model: hbheag
  bounding_box:
  - 0.03577
  - 0.0359248
  - 0.091956
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0959781
- type: DatasetObject
  name: distractor_tea_bag
  category: tea_bag
  model: kmvcrb
  bounding_box:
  - 0.0507929
  - 0.0391162
  - 0.0250638
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0625319
immutables: []
