task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the marker from the cup
instruction_obj_to_replace: marker
instruction_target_to_replace: cup
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.1225221
    - 0.5282708
    - 0.365561
    rot:
    - 0.3389426
    - -0.4991247
    - -0.6572071
    - 0.4517424
  cam2:
    pos:
    - 0.1803726
    - -0.5866698
    - 0.4270061
    rot:
    - 0.3682381
    - -0.149066
    - -0.3581127
    - 0.8449469
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.1390538
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_hamper
  category: hamper
  model: qhdikw
  bounding_box:
  - 0.1
  - 0.1
  - 0.1501503
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.1250752
- type: DatasetObject
  name: distractor_lime
  category: lime
  model: iwjcjp
  bounding_box:
  - 0.0780001
  - 0.059701
  - 0.0595602
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.0797802
- type: DatasetObject
  name: distractor_plier
  category: plier
  model: zwzncq
  bounding_box:
  - 0.1
  - 0.0290735
  - 0.0057135
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0528568
immutables:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0819912
