task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the pen from the mug
instruction_obj_to_replace: pen
instruction_target_to_replace: mug
instruction_verb_to_replace: pick
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.308613
    - -0.314825
    - 0.236702
    rot:
    - 0.4894354
    - -0.1128228
    - -0.1808426
    - 0.8455885
  cam2:
    pos:
    - 0.1925156
    - 0.330672
    - 0.2406243
    rot:
    - 0.2916621
    - -0.403109
    - -0.7232927
    - 0.4788361
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.1437248
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_wine_bottle
  category: wine_bottle
  model: hlzfxw
  bounding_box:
  - 0.0585717
  - 0.0585691
  - 0.2522422
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.1761212
- type: DatasetObject
  name: distractor_tray
  category: tray
  model: coqeme
  bounding_box:
  - 0.063813
  - 0.1
  - 0.0080665
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0540333
- type: DatasetObject
  name: distractor_hammer
  category: hammer
  model: fcrlbo
  bounding_box:
  - 0.1
  - 0.0414141
  - 0.012226
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.056113
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0819912
