task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the pen in the mug
instruction_obj_to_replace: pen
instruction_target_to_replace: mug
instruction_verb_to_replace: put
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.0631453
    - -0.6094259
    - 0.6817056
    rot:
    - 0.4470957
    - -0.1362101
    - -0.2527913
    - 0.8471415
  cam2:
    pos:
    - -0.0506692
    - 0.6387828
    - 0.5261675
    rot:
    - 0.2043131
    - -0.5026905
    - -0.7577983
    - 0.3623537
main_objects:
- type: DatasetObject
  name: pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1189699
  - 0.0105993
  - 0.009367
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0546835
target_objects:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_allen_wrench
  category: allen_wrench
  model: neqlcn
  bounding_box:
  - 0.1
  - 0.0216
  - 0.0037425
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0518713
- type: DatasetObject
  name: distractor_softball
  category: softball
  model: erhbze
  bounding_box:
  - 0.0975069
  - 0.0974477
  - 0.0978493
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0989247
- type: DatasetObject
  name: distractor_pear
  category: pear
  model: clvnqe
  bounding_box:
  - 0.0933374
  - 0.0726271
  - 0.0773291
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0886646
immutables: []
