task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the lid from the pot
instruction_obj_to_replace: lid
instruction_target_to_replace: pot
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - -0.0715256
    - -0.3527618
    - 0.4095998
    rot:
    - 0.4162337
    - -0.4159783
    - -0.5350331
    - 0.6061775
  cam2:
    pos:
    - 0.0639672
    - 0.4004726
    - 0.32938
    rot:
    - 0.3057832
    - -0.5055823
    - -0.6898285
    - 0.4183536
main_objects:
- type: DatasetObject
  name: lid
  category: lid
  model: zkderg
  bounding_box:
  - 0.0761192
  - 0.0761192
  - 0.0330479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.1578014
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_toasting_fork
  category: toasting_fork
  model: osrfkc
  bounding_box:
  - 0.1
  - 0.0172655
  - 0.005388
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.052694
- type: DatasetObject
  name: distractor_pill_bottle
  category: pill_bottle
  model: csvdbe
  bounding_box:
  - 0.0388496
  - 0.0388496
  - 0.0546776
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.0773388
- type: DatasetObject
  name: distractor_stapler
  category: stapler
  model: kgnsas
  bounding_box:
  - 0.0874299
  - 0.0182303
  - 0.0450232
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0725117
immutables:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0906387
