task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Pick up the marker from the cup and put it on the table
instruction_obj_to_replace: marker
instruction_target_to_replace: ''
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_1_int:
  - Drawers_Near_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.1972866
    - -0.3219055
    - 0.3194076
    rot:
    - 0.4507052
    - -0.1780521
    - -0.3795988
    - 0.7880781
  cam2:
    pos:
    - 0.2214199
    - 0.4326601
    - 0.2749901
    rot:
    - 0.0112578
    - -0.4829886
    - -0.827703
    - 0.2854873
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.154
  - 0.176
  - 0.056298
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.504
  - 0.544
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.14
  - 0.576
  - 0.0557962
- type: DatasetObject
  name: distractor_pen
  category: pen
  model: ubwjqa
  bounding_box:
  - 0.1
  - 0.0089092
  - 0.0078734
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.532
  - 0.176
  - 0.0539367
immutables: []
