task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the towel in the box
instruction_obj_to_replace: towel
instruction_target_to_replace: box
instruction_verb_to_replace: put
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.3018432
    - 0.4666669
    - 0.4114184
    rot:
    - 0.249163
    - -0.4559791
    - -0.778299
    - 0.3524932
  cam2:
    pos:
    - 0.0179389
    - -0.5512427
    - 0.426541
    rot:
    - 0.4238775
    - -0.2191007
    - -0.4362854
    - 0.7628747
main_objects:
- type: DatasetObject
  name: towel
  category: dishtowel
  model: dtfspn
  bounding_box:
  - 0.1081742
  - 0.1478261
  - 0.0221116
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0610558
target_objects:
- type: DatasetObject
  name: box
  category: storage_box
  model: izcglf
  bounding_box:
  - 0.1684259
  - 0.17
  - 0.0894269
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0947135
distractors:
- type: DatasetObject
  name: distractor_hamburger_bun
  category: hamburger_bun
  model: fqxumh
  bounding_box:
  - 0.08664
  - 0.0849436
  - 0.0263912
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0631956
- type: DatasetObject
  name: distractor_jug
  category: jug
  model: gjgwvi
  bounding_box:
  - 0.0716472
  - 0.1
  - 0.1521222
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.1260611
- type: DatasetObject
  name: distractor_carrot
  category: carrot
  model: nktmff
  bounding_box:
  - 0.0912197
  - 0.0260657
  - 0.0236784
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.3
  - 0.0618392
immutables: []
