task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the red object in the bowl
instruction_obj_to_replace: object
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.1186316
    - 0.3087799
    - 0.3018772
    rot:
    - 0.3644775
    - -0.3672894
    - -0.5432882
    - 0.6611298
  cam2:
    pos:
    - 0.122938
    - -0.429936
    - 0.2892466
    rot:
    - 0.6189636
    - -0.1269128
    - -0.4531488
    - 0.6288349
main_objects:
- type: PrimitiveObject
  name: red_object
  primitive_type: Cube
  rgba:
  - 0.85
  - 0.1
  - 0.1
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_round_bottom_flask
  category: round_bottom_flask
  model: hmzafz
  bounding_box:
  - 0.0818039
  - 0.0818039
  - 0.2176096
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.1588048
- type: DatasetObject
  name: distractor_carving_knife
  category: carving_knife
  model: awvoox
  bounding_box:
  - 0.1
  - 0.0133686
  - 0.0075487
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0537744
- type: DatasetObject
  name: distractor_tablespoon
  category: tablespoon
  model: mwzxal
  bounding_box:
  - 0.1
  - 0.0183986
  - 0.0078308
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0539154
immutables: []
