task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the lid off the pot
instruction_obj_to_replace: lid
instruction_target_to_replace: pot
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - -0.1309187
    - -0.2769083
    - 0.7067526
    rot:
    - 0.4772853
    - -0.243685
    - -0.409029
    - 0.7385876
  cam2:
    pos:
    - -0.2159796
    - 0.4407388
    - 0.5364212
    rot:
    - 0.405169
    - -0.4710755
    - -0.6392556
    - 0.4530763
main_objects:
- type: DatasetObject
  name: lid
  category: lid
  model: zkderg
  bounding_box:
  - 0.0761192
  - 0.0761192
  - 0.0330479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.1578014
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_tablefork
  category: tablefork
  model: uodzrq
  bounding_box:
  - 0.1
  - 0.0126529
  - 0.0063285
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.0531643
- type: DatasetObject
  name: distractor_table_knife
  category: table_knife
  model: nmkend
  bounding_box:
  - 0.1
  - 0.0105588
  - 0.0021862
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.0510931
- type: DatasetObject
  name: distractor_beefsteak_tomato
  category: beefsteak_tomato
  model: eevvzv
  bounding_box:
  - 0.0551043
  - 0.0539619
  - 0.0716401
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0858201
immutables:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0906387
