task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the can from the bowl
instruction_obj_to_replace: can
instruction_target_to_replace: bowl
instruction_verb_to_replace: pick
supported_scenes:
  Wainscott_0_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.3766383
    - 0.4924901
    - 0.444242
    rot:
    - 0.0561561
    - -0.5567525
    - -0.8213856
    - 0.1104483
  cam2:
    pos:
    - 0.0526131
    - -0.3352111
    - 0.3301058
    rot:
    - 0.4558011
    - -0.2976487
    - -0.4565616
    - 0.703706
main_objects:
- type: DatasetObject
  name: can
  category: can
  model: moeqjz
  bounding_box:
  - 0.1107923
  - 0.1107923
  - 0.1438354
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.18
  - 0.1341344
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_potato
  category: potato
  model: ljfitc
  bounding_box:
  - 0.0762014
  - 0.060351
  - 0.057834
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.35
  - 0.42
  - 0.078917
- type: DatasetObject
  name: distractor_volleyball
  category: volleyball
  model: nofzds
  bounding_box:
  - 0.0997848
  - 0.1
  - 0.1000092
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.42
  - 0.1000046
- type: DatasetObject
  name: distractor_erlenmeyer_flask
  category: erlenmeyer_flask
  model: bpwjxr
  bounding_box:
  - 0.0776034
  - 0.0776101
  - 0.1531681
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.35
  - 0.18
  - 0.1265841
immutables:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.18
  - 0.0740878
