task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the marker in the pot
instruction_obj_to_replace: marker
instruction_target_to_replace: pot
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.0353081
    - 0.4018187
    - 0.4510215
    rot:
    - 0.2817714
    - -0.6533585
    - -0.6533739
    - 0.2585151
  cam2:
    pos:
    - -0.0834536
    - -0.2834103
    - 0.407184
    rot:
    - 0.6830988
    - -0.2262786
    - -0.2365433
    - 0.6528562
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.056298
target_objects:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0906387
distractors:
- type: DatasetObject
  name: distractor_stapler
  category: stapler
  model: kgnsas
  bounding_box:
  - 0.0874299
  - 0.0182303
  - 0.0450232
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0725117
- type: DatasetObject
  name: distractor_reagent_bottle
  category: reagent_bottle
  model: uaijua
  bounding_box:
  - 0.0902924
  - 0.0902924
  - 0.1847585
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.1423793
- type: DatasetObject
  name: distractor_hamburger_bun
  category: hamburger_bun
  model: fqxumh
  bounding_box:
  - 0.08664
  - 0.0849436
  - 0.0263912
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0631956
immutables: []
