task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the marker from the bowl
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: pick
supported_scenes:
  Wainscott_0_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - -0.0160244
    - -0.4004213
    - 0.2356631
    rot:
    - 0.5148336
    - -0.2387908
    - -0.3649718
    - 0.7380521
  cam2:
    pos:
    - 0.3019745
    - 0.4937814
    - 0.5780066
    rot:
    - 0.1938215
    - -0.3905798
    - -0.8301216
    - 0.3475324
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.15
  - 0.18
  - 0.1232469
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_pocketknife
  category: pocketknife
  model: ngtgdn
  bounding_box:
  - 0.1
  - 0.0215911
  - 0.0058475
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.35
  - 0.42
  - 0.0529238
- type: DatasetObject
  name: distractor_tweezers
  category: tweezers
  model: ngwoat
  bounding_box:
  - 0.0048518
  - 0.0320922
  - 0.0024996
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.42
  - 0.0512499
- type: DatasetObject
  name: distractor_canned_food
  category: canned_food
  model: byakrm
  bounding_box:
  - 0.0577961
  - 0.0577961
  - 0.081812
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.35
  - 0.18
  - 0.090906
immutables:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.15
  - 0.18
  - 0.0740878
