task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the orange object in the bowl
instruction_obj_to_replace: object
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Dining_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.1266216
    - -0.5185954
    - 0.4552473
    rot:
    - 0.4913199
    - -0.1760016
    - -0.3072537
    - 0.7957534
  cam2:
    pos:
    - 0.043808
    - 0.5287548
    - 0.4589733
    rot:
    - 0.200346
    - -0.4729669
    - -0.7792256
    - 0.3591256
main_objects:
- type: PrimitiveObject
  name: orange_object
  primitive_type: Cube
  rgba:
  - 0.95
  - 0.4
  - 0.05
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.28
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.12
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_hamburger
  category: hamburger
  model: fyswch
  bounding_box:
  - 0.1
  - 0.0931673
  - 0.0648095
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.18
  - 0.28
  - 0.0824048
- type: DatasetObject
  name: distractor_shaker
  category: shaker
  model: hbheag
  bounding_box:
  - 0.03577
  - 0.0359248
  - 0.091956
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.42
  - 0.12
  - 0.0959781
- type: DatasetObject
  name: distractor_tray
  category: tray
  model: coqeme
  bounding_box:
  - 0.063813
  - 0.1
  - 0.0080665
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.3
  - 0.0540333
immutables: []
