task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the lid off of the pot
instruction_obj_to_replace: lid
instruction_target_to_replace: pot
instruction_verb_to_replace: pick
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.1323739
    - -0.4504519
    - 0.5070765
    rot:
    - 0.6182696
    - -0.2306244
    - -0.2571283
    - 0.7060029
  cam2:
    pos:
    - 0.1920879
    - 0.6846938
    - 0.5264407
    rot:
    - 0.2003852
    - -0.5581376
    - -0.7469697
    - 0.3006068
main_objects:
- type: DatasetObject
  name: lid
  category: lid
  model: zkderg
  bounding_box:
  - 0.0761192
  - 0.0761192
  - 0.0330479
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.1578014
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_mug
  category: mug
  model: kitxam
  bounding_box:
  - 0.0640022
  - 0.0858475
  - 0.0646612
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.0823306
- type: DatasetObject
  name: distractor_screwdriver
  category: screwdriver
  model: uajlga
  bounding_box:
  - 0.1
  - 0.0092784
  - 0.0092209
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.0546105
- type: DatasetObject
  name: distractor_blackboard_eraser
  category: blackboard_eraser
  model: oynrtw
  bounding_box:
  - 0.1
  - 0.0333333
  - 0.0242238
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0621119
immutables:
- type: DatasetObject
  name: pot
  category: saucepot
  model: ozrwwk
  bounding_box:
  - 0.1058229
  - 0.17
  - 0.0812774
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0906387
