task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the marker inside the mug cup
instruction_obj_to_replace: marker
instruction_target_to_replace: mug cup
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.3619371
    - 0.6137135
    - 0.4519156
    rot:
    - 0.0551698
    - -0.5966718
    - -0.7911585
    - 0.1225043
  cam2:
    pos:
    - 0.0518266
    - -0.73597
    - 0.4682291
    rot:
    - 0.5218449
    - -0.2565163
    - -0.2947614
    - 0.7582829
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.056298
target_objects:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_carrot
  category: carrot
  model: nktmff
  bounding_box:
  - 0.0912197
  - 0.0260657
  - 0.0236784
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.0618392
- type: DatasetObject
  name: distractor_duct_tape
  category: duct_tape
  model: htrage
  bounding_box:
  - 0.1
  - 0.0902877
  - 0.0293116
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0646558
- type: DatasetObject
  name: distractor_zucchini
  category: zucchini
  model: yhhkxf
  bounding_box:
  - 0.1
  - 0.0399945
  - 0.0373826
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.25
  - 0.0686914
immutables: []
