task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick up the green object from the table and put it in the bowl
instruction_obj_to_replace: object
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - -0.0911607
    - -0.3505385
    - 0.4103574
    rot:
    - 0.5010745
    - -0.4128471
    - -0.4500838
    - 0.6131119
  cam2:
    pos:
    - -0.0398682
    - 0.4660799
    - 0.3991122
    rot:
    - 0.3738833
    - -0.5445575
    - -0.6357084
    - 0.3994287
main_objects:
- type: PrimitiveObject
  name: green_object
  primitive_type: Cube
  rgba:
  - 0.1
  - 0.7
  - 0.25
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_grape
  category: grape
  model: uprbwp
  bounding_box:
  - 0.1
  - 0.0617632
  - 0.0602211
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.0801106
- type: DatasetObject
  name: distractor_sushi
  category: sushi
  model: akpnxn
  bounding_box:
  - 0.0354409
  - 0.0362632
  - 0.0241283
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0620642
- type: DatasetObject
  name: distractor_parer
  category: parer
  model: zpkhwi
  bounding_box:
  - 0.1
  - 0.0126289
  - 0.006733
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0533665
immutables: []
