task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick up the orange object and put it in the bowl.
instruction_obj_to_replace: object
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.3615103
    - 0.498113
    - 0.3651057
    rot:
    - 0.0860997
    - -0.5449914
    - -0.820098
    - 0.1516923
  cam2:
    pos:
    - 0.1002135
    - -0.3860416
    - 0.6049155
    rot:
    - 0.4224937
    - -0.2455746
    - -0.4181862
    - 0.7657105
main_objects:
- type: PrimitiveObject
  name: orange_object
  primitive_type: Cube
  rgba:
  - 0.95
  - 0.4
  - 0.05
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.088
  - 0.088
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.22
  - 0.193924
  - 0.0623446
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.288
  - 0.272
  - 0.0811723
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.08
  - 0.288
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.304
  - 0.088
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.072
  - 0.184
  - 0.0562801
immutables: []
