task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the bowl.
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: pick
supported_scenes:
  Pomaria_1_int:
  - Table
camera_extrinsics:
  cam1:
    pos:
    - 0.3797844
    - 0.6042511
    - 0.4535853
    rot:
    - 0.1300342
    - -0.4545097
    - -0.8556957
    - 0.2104683
  cam2:
    pos:
    - 0.2155785
    - -0.4720695
    - 0.4130151
    rot:
    - 0.5951717
    - -0.1135698
    - -0.1559618
    - 0.7800952
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.1232469
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_sponge
  category: sponge
  model: aewrov
  bounding_box:
  - 0.1
  - 0.0666667
  - 0.02
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.455
  - 0.06
- type: DatasetObject
  name: distractor_peach
  category: peach
  model: wrutgk
  bounding_box:
  - 0.0884365
  - 0.0909698
  - 0.0949293
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.455
  - 0.0974647
- type: DatasetObject
  name: distractor_open_end_wrench
  category: open_end_wrench
  model: klnawb
  bounding_box:
  - 0.1
  - 0.0272955
  - 0.0051241
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.195
  - 0.0525621
immutables:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.195
  - 0.0740878
