task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the marker in the bowl
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - -0.3224765
    - -0.5183381
    - 0.4122756
    rot:
    - 0.568751
    - -0.4028877
    - -0.4408541
    - 0.5655541
  cam2:
    pos:
    - 0.0663727
    - 0.5209122
    - 0.4186865
    rot:
    - 0.3732027
    - -0.5444653
    - -0.5996621
    - 0.4524186
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.056298
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_can_of_baking_mix
  category: can_of_baking_mix
  model: blrqqz
  bounding_box:
  - 0.0939999
  - 0.0939998
  - 0.109535
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.1047675
- type: DatasetObject
  name: distractor_erlenmeyer_flask
  category: erlenmeyer_flask
  model: bpwjxr
  bounding_box:
  - 0.0776034
  - 0.0776101
  - 0.1531681
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.1265841
- type: DatasetObject
  name: distractor_box_of_cereal
  category: box_of_cereal
  model: pfwgkm
  bounding_box:
  - 0.035
  - 0.1
  - 0.115
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.2
  - 0.375
  - 0.1075001
immutables: []
