task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick the marker and put it in the bowl
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.2885448
    - 0.5138503
    - 0.5129482
    rot:
    - 0.1113818
    - -0.4549545
    - -0.8543556
    - 0.2251378
  cam2:
    pos:
    - -0.0287674
    - -0.3373308
    - 0.4425981
    rot:
    - 0.4122806
    - -0.334783
    - -0.5274527
    - 0.663128
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.056298
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0740878
distractors:
- type: DatasetObject
  name: distractor_rubber_eraser
  category: rubber_eraser
  model: cungod
  bounding_box:
  - 0.05
  - 0.0213523
  - 0.0114031
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.0557016
- type: DatasetObject
  name: distractor_pill_bottle
  category: pill_bottle
  model: csvdbe
  bounding_box:
  - 0.0388496
  - 0.0388496
  - 0.0546776
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0773388
- type: DatasetObject
  name: distractor_water_bottle
  category: water_bottle
  model: lzdzkk
  bounding_box:
  - 0.0873897
  - 0.0864275
  - 0.2549802
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.25
  - 0.1774901
immutables: []
