task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Remove the marker from the mug
instruction_obj_to_replace: marker
instruction_target_to_replace: mug
instruction_verb_to_replace: pick
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.1658986
    - 0.6252171
    - 0.3617703
    rot:
    - 0.203526
    - -0.5629988
    - -0.7503158
    - 0.2804206
  cam2:
    pos:
    - -0.1362399
    - -0.6074925
    - 0.4217053
    rot:
    - 0.5889034
    - -0.2345001
    - -0.319122
    - 0.7045308
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.1390538
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_drill
  category: drill
  model: nzgmza
  bounding_box:
  - 0.0372309
  - 0.1
  - 0.1252277
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.1126139
- type: DatasetObject
  name: distractor_jug
  category: jug
  model: gjgwvi
  bounding_box:
  - 0.0716472
  - 0.1
  - 0.1521222
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.1260611
- type: DatasetObject
  name: distractor_wire_cutter
  category: wire_cutter
  model: ugbval
  bounding_box:
  - 0.1
  - 0.0359596
  - 0.0070931
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0535466
immutables:
- type: DatasetObject
  name: mug
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0819912
