task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: stack
instruction: Stack the cups together
instruction_obj_to_replace: cups
instruction_target_to_replace: cups
instruction_verb_to_replace: stack
supported_scenes:
  office_cubicles_left:
  - Circular_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.1078482
    - 0.3767776
    - 0.4694734
    rot:
    - 0.2343302
    - -0.4135273
    - -0.7115269
    - 0.5175074
  cam2:
    pos:
    - 0.063432
    - -0.2790187
    - 0.4044757
    rot:
    - 0.4951597
    - -0.279064
    - -0.5135857
    - 0.6427829
main_objects:
- type: DatasetObject
  name: cup_1
  category: mug
  model: kitxam
  bounding_box:
  - 0.0640022
  - 0.0858475
  - 0.0646612
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.132
  - 0.11
  - 0.0823306
target_objects:
- type: DatasetObject
  name: cup_2
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.432
  - 0.34
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.36
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.456
  - 0.11
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.288
  - 0.44
  - 0.0562801
immutables: []
