task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Pick up the marker and put it in the cup
instruction_obj_to_replace: marker
instruction_target_to_replace: cup
instruction_verb_to_replace: put
supported_scenes:
  Benevolence_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.0886488
    - 0.4223848
    - 0.4662603
    rot:
    - 0.394227
    - -0.3450233
    - -0.6083528
    - 0.5961969
  cam2:
    pos:
    - 0.1338937
    - -0.5526269
    - 0.3829756
    rot:
    - 0.5537302
    - -0.1638614
    - -0.2354987
    - 0.7817114
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.28
  - 0.056298
target_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.12
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_pruner
  category: pruner
  model: lucqrs
  bounding_box:
  - 0.0293022
  - 0.0669072
  - 0.2279074
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.28
  - 0.1639537
- type: DatasetObject
  name: distractor_banana
  category: banana
  model: verqwv
  bounding_box:
  - 0.1
  - 0.0313722
  - 0.0157945
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.12
  - 0.0578973
- type: DatasetObject
  name: distractor_table_knife
  category: table_knife
  model: nmkend
  bounding_box:
  - 0.1
  - 0.0105588
  - 0.0021862
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.2
  - 0.0510931
immutables: []
