task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: pick
instruction: Take the marker out of the bowl
instruction_obj_to_replace: marker
instruction_target_to_replace: bowl
instruction_verb_to_replace: pick
supported_scenes:
  office_cubicles_left:
  - Office_Desk
camera_extrinsics:
  cam1:
    pos:
    - 0.2683631
    - 0.3783897
    - 0.4403776
    rot:
    - 0.1386919
    - -0.5034372
    - -0.8127185
    - 0.2584651
  cam2:
    pos:
    - 0.2494383
    - -0.4371407
    - 0.3465157
    rot:
    - 0.6358208
    - -0.1658518
    - -0.1656638
    - 0.7353779
main_objects:
- type: DatasetObject
  name: marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1002858
  - 0.0126068
  - 0.012596
  orientation:
  - 0.0
  - 0.7071068
  - 0.0
  - 0.7071068
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.1232469
target_objects: []
distractors:
- type: DatasetObject
  name: distractor_toasting_fork
  category: toasting_fork
  model: osrfkc
  bounding_box:
  - 0.1
  - 0.0172655
  - 0.005388
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.42
  - 0.052694
- type: DatasetObject
  name: distractor_toy_figure
  category: toy_figure
  model: jddrck
  bounding_box:
  - 0.0823193
  - 0.0870553
  - 0.15
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.42
  - 0.125
- type: DatasetObject
  name: distractor_hamburger_bun
  category: hamburger_bun
  model: fqxumh
  bounding_box:
  - 0.08664
  - 0.0849436
  - 0.0263912
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.18
  - 0.0631956
immutables:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.17
  - 0.1498503
  - 0.0481754
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.18
  - 0.0740878
