task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the orange object in the bowl
instruction_obj_to_replace: object
instruction_target_to_replace: bowl
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Drawers_Near_Table
camera_extrinsics:
  cam1:
    pos:
    - 0.2314073
    - 0.4503975
    - 0.440619
    rot:
    - 0.1233562
    - -0.7646653
    - -0.533863
    - 0.3392058
  cam2:
    pos:
    - 0.2940677
    - -0.5341096
    - 0.4269243
    rot:
    - 0.59185
    - 0.0769652
    - -0.0085475
    - 0.8023197
main_objects:
- type: PrimitiveObject
  name: orange_object
  primitive_type: Cube
  rgba:
  - 0.95
  - 0.4
  - 0.05
  - 1.0
  bounding_box:
  - 0.05
  - 0.05
  - 0.05
  scale:
  - 0.05
  - 0.05
  - 0.05
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.154
  - 0.176
  - 0.0750001
target_objects:
- type: DatasetObject
  name: bowl
  category: bowl
  model: ckxwea
  bounding_box:
  - 0.22
  - 0.193924
  - 0.0623446
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.504
  - 0.544
  - 0.0811723
distractors:
- type: DatasetObject
  name: distractor_teaspoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.14
  - 0.576
  - 0.0538992
- type: DatasetObject
  name: distractor_masking_tape
  category: masking_tape
  model: vpgzne
  bounding_box:
  - 0.0501454
  - 0.0499654
  - 0.0115923
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.532
  - 0.176
  - 0.0557962
- type: DatasetObject
  name: distractor_marker
  category: marker
  model: qemval
  bounding_box:
  - 0.1
  - 0.0125709
  - 0.0125601
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.336
  - 0.704
  - 0.0562801
immutables: []
