task:
  type: DummyTask
  termination_config: {}
  reward_config: {}
task_type: put
instruction: Put the spoon in the cup
instruction_obj_to_replace: spoon
instruction_target_to_replace: cup
instruction_verb_to_replace: put
supported_scenes:
  Pomaria_1_int:
  - Kitchen_Counter
camera_extrinsics:
  cam1:
    pos:
    - 0.1104217
    - 0.4533234
    - 0.5521768
    rot:
    - 0.1872058
    - -0.5108588
    - -0.7812957
    - 0.3058664
  cam2:
    pos:
    - 6.21e-05
    - -0.3647466
    - 0.3645111
    rot:
    - 0.4413707
    - -0.3014084
    - -0.4679785
    - 0.7038046
main_objects:
- type: DatasetObject
  name: spoon
  category: teaspoon
  model: wzsvzv
  bounding_box:
  - 0.0989419
  - 0.0221837
  - 0.0077984
  orientation:
  - 0.0
  - 0.0
  - 0.7071068
  - 0.7071068
  relative_bbox_position:
  - 0.28
  - 0.35
  - 0.0538992
target_objects:
- type: DatasetObject
  name: cup
  category: mug
  model: jgethp
  bounding_box:
  - 0.1127337
  - 0.1368154
  - 0.0639822
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.15
  - 0.0819912
distractors:
- type: DatasetObject
  name: distractor_mouse
  category: mouse
  model: oydobn
  bounding_box:
  - 0.0310995
  - 0.0195964
  - 0.0112779
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.12
  - 0.35
  - 0.055639
- type: DatasetObject
  name: distractor_sourdough
  category: sourdough
  model: jgydml
  bounding_box:
  - 0.089787
  - 0.0798728
  - 0.0522223
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.28
  - 0.15
  - 0.0761112
- type: DatasetObject
  name: distractor_half_bagel
  category: half_bagel
  model: hsvakn
  bounding_box:
  - 0.1
  - 0.0660361
  - 0.0367416
  orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  relative_bbox_position:
  - 0.3
  - 0.25
  - 0.0683709
immutables: []
